language: ruby
script : script/cibuild
rvm:
- 2.2
- 2.1
- 2.0
cache: bundler
sudo: false
notifications:
  email: false


matrix:
  include:
    - # Ruby 1.9
      rvm: 1.9
      env: JEKYLL_VERSION=2.0
  fast_finish: true
env:
  - ""
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
